### ISSUE TITLE
[Question] What problem Snarkynet is solving?

### ISSUE THREAD

**Issue by nscotto** [Makalfo/SnarkyNet-MNIST-Digits#1]
Hi, no offense in that question, I am just trying to understand what can be done with Snarkynet.
When AI computation can be done on the client side - why would we need a SnarkyJS implementation of neural network?
Is it to prove that a Neural Network is valid?

Could you cite me examples where this would be needed?
Thank you, I believe the AI/zkp mix is the best technology coming up

**Comment by Makalfo** [comment]
If the computation is done outside of the circuit, it can be easily faked or hacked. Let's say you were calling something externally, they could fake the external resource and inject it with whatever result gives them what they want.

In the world of zero-knowledge proofs, you'd want to ensure that it's all in the circuit for that. In the world of smart-contracts, you want to ensure your contract is secure to protect any funds or the project, overall.

**Comment by nscotto** [comment]
Mh I see...
I am quite interested in seeing the project growing and I would be very happy to contribute, 
Would you be available for an exchange?

**Comment by Makalfo** [comment]
DM me on discord: Makalfo#7996
